---
stages:
  - lint
  - test
  - molecule
  - changes
  - push

variables:
  GITHUB_USER: lotusnoir


##################################################
# LINT
##################################################
yamllint:
  stage: lint
  image: sdesbure/yamllint
  before_script:
    - yamllint --version
  script:
    - yamllint .

ansible-lint:
  stage: lint
  image: lotusnoir/ansible_play
  script:
    - ansible-lint .


##################################################
# TEST / SECU
##################################################
include:
  - template: Security/Secret-Detection.gitlab-ci.yml

######################################################
# RUN MOLECULE FOR EACH DISTRIB
######################################################
molecule_ubuntu22:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=ubuntu22 molecule test
molecule_ubuntu20:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
    MOLECULE_DOCKER_COMMAND: "--cap-add NET_ADMIN"
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=ubuntu20 molecule test
molecule_ubuntu18:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
    MOLECULE_DOCKER_COMMAND: "--cap-add NET_ADMIN"
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=ubuntu18 molecule test
molecule_debian10:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=debian10 molecule test
molecule_debian11:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=debian11 molecule test
molecule_debian12:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=debian12 molecule test
molecule_oraclelinux8:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=oraclelinux8 molecule test
molecule_oraclelinux9:
  stage: molecule
  image: lotusnoir/molecule_play
  services:
    - docker:dind
  variables:
    PY_COLORS: 1
  needs:
    - yamllint
    - ansible-lint
  script:
    - MOLECULE_DISTRIB=oraclelinux9 molecule test

######################################################
# GENERATE CHANGELOG FILE
######################################################
changelog:
  stage: changes
  image: node:19
  needs:
    - molecule_ubuntu22
    - molecule_ubuntu20
    - molecule_ubuntu18
    - molecule_debian10
    - molecule_debian11
    - molecule_debian12
    - molecule_oraclelinux8
    - molecule_oraclelinux9
  artifacts:
    paths:
      - CHANGELOG.md
    expire_in: 1 day
  before_script:
    - npm install -g auto-changelog
  script:
    - auto-changelog -t keepachangelog --sort-commits date-desc --hide-empty-releases --hide-credit -l 10 -b 10


##################################################
# PUSH CODE WHEN ALL TEST OK
##################################################
push_src_on_github:
  stage: push
  image: alpine:latest
  needs:
    - changelog
  before_script:
    - apk add git openssh-client
    - eval $(ssh-agent -s)
    - echo "${GITHUB_USER_PRIVATE_KEY}" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tUser ansible\n\tStrictHostKeyChecking no\n\tForwardAgent yes\n\n" > ~/.ssh/config
    - git config --global user.email "${GITHUB_USER_EMAIL}"
    - git config --global user.name "${GITHUB_USER}"
    - git config --global init.defaultBranch main
    - COMMENT=$(git log -1 --pretty=%B | head -1)
  script:
    - git clone git@github.com:${GITHUB_USER}/ansible-apps_dhcpd_exporter.git /tmp/ansible-apps_dhcpd_exporter
    - find /tmp/ansible-apps_dhcpd_exporter -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf "{}" +;
    - rm -rf .git
    - cp -r . /tmp/ansible-apps_dhcpd_exporter/
    - cd /tmp/ansible-apps_dhcpd_exporter
    - git add -A
    - git commit -m "${COMMENT}" || echo "No changes, nothing to commit!"
    - git push --follow-tags
