---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: check-byte-order-marker
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-symlinks
      - id: detect-private-key
      - id: check-yaml
        files: .*\.(yaml|yml)$

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args:
          ["--ignore-unknown", "--no-error-on-unmatched-pattern", "!chart/**"]

  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.42.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--disable", "MD013 MD033"]

  # Lint: YAML
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file, yaml]
        entry: yamllint --strict -f parsable

  # Lint: Ansible
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v25.1.1
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
        entry: ansible-lint --force-color
        exclude: ^molecule/

  - repo: https://github.com/robertdebock/pre-commit
    rev: v1.5.2
    hooks:
      - id: ansible_role_find_unused_variable
      - id: ansible_role_find_empty_files
      - id: ansible_role_find_empty_directories
      # - id: ansible_role_fix_readability
      - id: ansible_role_find_undefined_handlers
      - id: ansible_role_find_unquoted_values

  # Secu: Detect secrets
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog --no-update git file://. --since-commit HEAD --only-verified --fail'
        language: system
        stages: ["commit", "push"]

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.23.1
    hooks:
      - id: gitleaks
