---
- name: "Check for dhcpd-exporter.py binary"
  ansible.builtin.stat:
    path: '{{ dhcpd_exporter_install_dir }}/dhcpd-exporter.py'
  changed_when: false
  register: dhcpd_exporter_install

- name: "Install tasks"
  when: not dhcpd_exporter_install.stat.exists
  block:
    - name: "Install requierements"
      ansible.builtin.package:
        name: '{{ dhcpd_exporter_packages }}'
        state: present
      register: pkg_result
      retries: 12
      delay: 10
      until: pkg_result is success

    - name: "Download dhcpd_exporter..."
      ansible.builtin.get_url:
        url: '{{ dhcpd_exporter_url }}'
        dest: '{{ dhcpd_exporter_install_dir }}/dhcpd-exporter.py'
        timeout: 120
        mode: '0755'

- name: "Create systemd for dhcpd_exporter"
  ansible.builtin.template:
    src: 'dhcpd_exporter.service.j2'
    dest: '/etc/systemd/system/dhcpd_exporter.service'
    mode: '0644'
  notify: "Restart dhcpd_exporter"

- name: "Enable and Start dhcpd_exporter.service"
  ansible.builtin.service:
    name: dhcpd_exporter
    state: started
    enabled: true
    daemon_reload: true
