---
### Checks
- name: Import check tasks
  ansible.builtin.import_tasks: check.yml

### Import vars
- name: add OS specific variables
  ansible.builtin.include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - 'main.yml'
      paths:
        - 'vars'
  loop_control:
    loop_var: vars_file

### Install
- name: Import install tasks
  ansible.builtin.import_tasks: install.yml
