---
dependency:
  name: galaxy

driver:
  name: docker

scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    # - verify
    - destroy

platforms:
  - name: apps-dhcpd-exporter-${MOLECULE_DISTRIB:-debian12}
    image: lotusnoir/ansible_molecule_test_images:${MOLECULE_DISTRIB:-debian12}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    docker_host: "${DOCKER_HOST:-unix://var/run/docker.sock}"
    pre_build_image: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw

provisioner:
  name: ansible
  connection_options:
    ansible_remote_tmp: /tmp
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml

verifier:
  name: ansible
